#!/bin/bash

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
NC='\033[0m'

echo -e "${BLUE}=== STARTING AJMAG HYPRLAND INSTALLATION ===${NC}"

# 1. Install YAY
if ! command -v yay &> /dev/null; then
    echo -e "${BLUE}Installing yay...${NC}"
    sudo pacman -S --needed git base-devel
    git clone https://aur.archlinux.org/yay.git
    cd yay
    makepkg -si
    cd ..
    rm -rf yay
fi

# 2. Install Packages
echo -e "${BLUE}Installing packages...${NC}"
sudo pacman -S --needed - < pkglist_native.txt
yay -S --needed - < pkglist_aur.txt

# 3. System Config
echo -e "${BLUE}Configuring system...${NC}"
sudo cp system/99-gpu-symlinks.rules /etc/udev/rules.d/
sudo udevadm control --reload-rules && sudo udevadm trigger

# 4. Enable Services
sudo systemctl enable --now preload
sudo systemctl enable --now bluetooth

# 5. Wallpapers
echo -e "${BLUE}Installing wallpapers...${NC}"
mkdir -p ~/Pictures/wallpapers
cp -r wallpapers/* ~/Pictures/wallpapers/

# 6. Dotfiles
echo -e "${BLUE}Installing dotfiles...${NC}"
CONFIG_DIR="$HOME/.config"
REPO_CONFIG_DIR="$(pwd)/.config"

install_config() {
    local folder=$1
    if [ -d "$REPO_CONFIG_DIR/$folder" ]; then
        if [ -d "$CONFIG_DIR/$folder" ]; then
            mv "$CONFIG_DIR/$folder" "$CONFIG_DIR/${folder}_backup_$(date +%s)"
        fi
        cp -r "$REPO_CONFIG_DIR/$folder" "$TARGET_CONFIG_DIR/"
    fi
}

folders=("hypr" "waybar" "kitty" "rofi" "swaync" "matugen" "wlogout" "spicetify")
for folder in "${folders[@]}"; do
    install_config "$folder"
done

# ZSH
if [ -f "$HOME/.zshrc" ]; then
    mv "$HOME/.zshrc" "$HOME/.zshrc_backup_$(date +%s)"
fi
cp "home_files/.zshrc" "$HOME/.zshrc"

# 7. Permissions & Fixes
chmod +x $HOME/.config/hypr/scripts/*.sh

# Monitor Failsafe
if [ ! -f "$HOME/.config/hypr/monitors.conf" ]; then
    touch "$HOME/.config/hypr/monitors.conf"
    echo "# Generated by install.sh" > "$HOME/.config/hypr/monitors.conf"
fi

# Set initial wallpaper symlink (to avoid errors)
FIRST_WALL=$(ls ~/Pictures/wallpapers/* | head -n 1)
if [ -n "$FIRST_WALL" ]; then
    ln -sf "$FIRST_WALL" "$HOME/.config/hypr/current_wallpaper"
fi

# 8. Zen Browser
echo -e "${BLUE}Configuring Zen Browser...${NC}"
ZEN_PROFILE=$(find "$HOME/.zen" -maxdepth 1 -type d -name "*.Default (release)" | head -n 1)
if [ -n "$ZEN_PROFILE" ]; then
    mkdir -p "$ZEN_PROFILE/chrome"
    echo '@import "matugen-colors.css";' > "$ZEN_PROFILE/chrome/userChrome.css"
    sed -i "s|output_path = .*|output_path = \"$ZEN_PROFILE/chrome/matugen-colors.css\"|" "$HOME/.config/matugen/config.toml"
fi

echo -e "${GREEN}=== INSTALLATION COMPLETE ===${NC}"
echo "Please restart your computer. Use Super+W to set theme."
