-- Generated by nwg-displays on 2026-06-10 at 02:51:51. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "1920x1080@60.02",
    position = "0x0",
    scale = 1.0
})
hl.monitor({
    output = "HDMI-A-2",
    mode = "2560x1440@60.0",
    position = "1920x0",
    scale = 1.0
})
