# Tags configuration updated for Hyprland v0.53+ (windowrulev2)

windowrulev2 = tag +multimedia_video, class:^([Mm]pv|vlc)$
windowrulev2 = tag +settings, class:^(nm-applet|nm-connection-editor|blueman-manager|org.gnome.FileRoller)$
windowrulev2 = tag +settings, class:^(org.gnome.DiskUtility|wihotspot(-gui)?)$
windowrulev2 = tag +viewer, class:^(org.gnome.SystemMonitor)$ 
windowrulev2 = tag +viewer, class:^(org.gnome.Evince)$ 
windowrulev2 = tag +viewer, class:^(eog|org.gnome.Loupe)$
